#!/usr/bin/env bash
# Offline scaffolder — creates the empty folder structure + zero-byte
# files matching the Erica Agent Platform repo layout. Intended for
# networks where github.com is blocked: run this script, then paste
# each file's content from the GitHub web view into the blank file.
#
# Usage:
#   ./scaffold.sh                  # creates ./finchat/
#   ./scaffold.sh path/to/dir      # creates ./path/to/dir/
#
# Maintenance: update the mkdir / touch lists below when tracked files
# change. No generator tool — keep it simple.
set -eu

TARGET="${1:-finchat}"
if [ -e "$TARGET" ] && [ "$(ls -A "$TARGET" 2>/dev/null)" ]; then
  echo "Refusing to scaffold into non-empty directory: $TARGET" >&2
  echo "Pass a fresh path as the first argument, or delete the existing one." >&2
  exit 1
fi
mkdir -p "$TARGET"
cd "$TARGET"

# --- Directories ---
mkdir -p "backend"
mkdir -p "backend/api_data/refund/alexm"
mkdir -p "backend/api_data/refund/aryash"
mkdir -p "backend/api_data/transfer/alexm"
mkdir -p "backend/api_data/transfer/aryash"
mkdir -p "backend/api_data/transfer/chrisp"
mkdir -p "backend/app"
mkdir -p "backend/app/agent"
mkdir -p "backend/app/agents"
mkdir -p "backend/app/agents/nodes"
mkdir -p "backend/app/agents/parsers"
mkdir -p "backend/app/agents/patterns"
mkdir -p "backend/app/agents/templates"
mkdir -p "backend/app/log"
mkdir -p "backend/app/models"
mkdir -p "backend/app/routers"
mkdir -p "backend/app/schemas"
mkdir -p "backend/app/seed"
mkdir -p "backend/app/services"
mkdir -p "backend/app/tools"
mkdir -p "backend/app/utils"
mkdir -p "backend/app/widgets"
mkdir -p "backend/docs"
mkdir -p "backend/docs/rag-data/better_money_rag_files"
mkdir -p "backend/migrations"
mkdir -p "backend/profile"
mkdir -p "backend/scripts"
mkdir -p "backend/tests"
mkdir -p "frontend"
mkdir -p "frontend/public"
mkdir -p "frontend/src"
mkdir -p "frontend/src/api"
mkdir -p "frontend/src/assets"
mkdir -p "frontend/src/components/agents"
mkdir -p "frontend/src/components/agents/graph"
mkdir -p "frontend/src/components/agents/graph/nodes"
mkdir -p "frontend/src/components/chat"
mkdir -p "frontend/src/components/layout"
mkdir -p "frontend/src/components/profiles"
mkdir -p "frontend/src/components/widgets"
mkdir -p "frontend/src/components/widgets/composites"
mkdir -p "frontend/src/pages"
mkdir -p "frontend/src/store"
mkdir -p "frontend/tests"

# --- Files (zero-byte) ---
touch ".gitignore"
touch "README.md"
touch "backend/.env.example"
touch "backend/alembic.ini"
touch "backend/api_data/refund/alexm/fee_refund.json"
touch "backend/api_data/refund/aryash/fee_refund.json"
touch "backend/api_data/transfer/alexm/transfer_cc.json"
touch "backend/api_data/transfer/alexm/transfer_m2m.json"
touch "backend/api_data/transfer/alexm/transfer_zelle.json"
touch "backend/api_data/transfer/aryash/transfer_cc.json"
touch "backend/api_data/transfer/aryash/transfer_m2m.json"
touch "backend/api_data/transfer/aryash/transfer_zelle.json"
touch "backend/api_data/transfer/chrisp/transfer_cc.json"
touch "backend/api_data/transfer/chrisp/transfer_m2m.json"
touch "backend/api_data/transfer/chrisp/transfer_zelle.json"
touch "backend/app/__init__.py"
touch "backend/app/agent/__init__.py"
touch "backend/app/agent/checkpointer.py"
touch "backend/app/agent/graph.py"
touch "backend/app/agent/nodes.py"
touch "backend/app/agent/presenter.py"
touch "backend/app/agent/state.py"
touch "backend/app/agents/__init__.py"
touch "backend/app/agents/escape.py"
touch "backend/app/agents/nodes/__init__.py"
touch "backend/app/agents/nodes/condition_node.py"
touch "backend/app/agents/nodes/interrupt_node.py"
touch "backend/app/agents/nodes/llm_node.py"
touch "backend/app/agents/nodes/parse_node.py"
touch "backend/app/agents/nodes/response_node.py"
touch "backend/app/agents/nodes/tool_call_node.py"
touch "backend/app/agents/nodes/tool_node.py"
touch "backend/app/agents/parsers/__init__.py"
touch "backend/app/agents/patterns/__init__.py"
touch "backend/app/agents/patterns/collect_one_slot.json"
touch "backend/app/agents/patterns/confirm_then_execute.json"
touch "backend/app/agents/predicates.py"
touch "backend/app/agents/runtime.py"
touch "backend/app/agents/state.py"
touch "backend/app/agents/template_compiler.py"
touch "backend/app/agents/template_loader.py"
touch "backend/app/agents/template_store.py"
touch "backend/app/agents/templates/__init__.py"
touch "backend/app/agents/templates/refund_fee.chat.json"
touch "backend/app/agents/templates/refund_fee.voice.json"
touch "backend/app/agents/templates/transfer_money.chat.json"
touch "backend/app/agents/templates/transfer_money.voice.json"
touch "backend/app/config.py"
touch "backend/app/database.py"
touch "backend/app/log/__init__.py"
touch "backend/app/log/config.py"
touch "backend/app/log/context.py"
touch "backend/app/log/middleware.py"
touch "backend/app/main.py"
touch "backend/app/models/__init__.py"
touch "backend/app/models/agent_definition.py"
touch "backend/app/models/chat.py"
touch "backend/app/models/file.py"
touch "backend/app/models/profile.py"
touch "backend/app/models/stream_events.py"
touch "backend/app/models/sub_agent_template.py"
touch "backend/app/models/widget_instance.py"
touch "backend/app/observability.py"
touch "backend/app/routers/__init__.py"
touch "backend/app/routers/agents.py"
touch "backend/app/routers/auth.py"
touch "backend/app/routers/chat.py"
touch "backend/app/routers/files.py"
touch "backend/app/routers/tools.py"
touch "backend/app/routers/widgets.py"
touch "backend/app/schemas/__init__.py"
touch "backend/app/schemas/auth.py"
touch "backend/app/schemas/chat.py"
touch "backend/app/schemas/file.py"
touch "backend/app/seed/profiles.json"
touch "backend/app/services/__init__.py"
touch "backend/app/services/enrichment.py"
touch "backend/app/services/indexing_service.py"
touch "backend/app/services/llm_service.py"
touch "backend/app/services/memory.py"
touch "backend/app/services/profile_service.py"
touch "backend/app/services/quick_actions.py"
touch "backend/app/services/rag_service.py"
touch "backend/app/services/refund_data_loader.py"
touch "backend/app/services/refund_service.py"
touch "backend/app/services/transaction_analyzer.py"
touch "backend/app/services/transaction_service.py"
touch "backend/app/services/transfer_data_loader.py"
touch "backend/app/services/transfer_service.py"
touch "backend/app/services/widget_service.py"
touch "backend/app/tools/__init__.py"
touch "backend/app/tools/agent_tool.py"
touch "backend/app/tools/base.py"
touch "backend/app/tools/data_tools.py"
touch "backend/app/tools/dynamic_sub_agent_tool.py"
touch "backend/app/tools/handoff.py"
touch "backend/app/tools/knowledge_search.py"
touch "backend/app/tools/refund_ops.py"
touch "backend/app/tools/refund_tool.py"
touch "backend/app/tools/tool_search.py"
touch "backend/app/tools/transfer_actions.py"
touch "backend/app/tools/transfer_ops.py"
touch "backend/app/tools/transfer_tool.py"
touch "backend/app/utils/__init__.py"
touch "backend/app/utils/templates.py"
touch "backend/app/widgets/__init__.py"
touch "backend/app/widgets/actions.py"
touch "backend/app/widgets/builders.py"
touch "backend/app/widgets/catalog.py"
touch "backend/app/widgets/summarizers.py"
touch "backend/docs/architecture.md"
touch "backend/docs/compound_response_plan.md"
touch "backend/docs/get_profile_data.md"
touch "backend/docs/rag-data/better_money_rag_files/00-site-overview.md"
touch "backend/docs/rag-data/better_money_rag_files/01-saving-budgeting.md"
touch "backend/docs/rag-data/better_money_rag_files/02-credit.md"
touch "backend/docs/rag-data/better_money_rag_files/03-debt-management.md"
touch "backend/docs/rag-data/better_money_rag_files/04-personal-banking.md"
touch "backend/docs/rag-data/better_money_rag_files/05-homeownership.md"
touch "backend/docs/rag-data/better_money_rag_files/06-investing-retirement.md"
touch "backend/docs/rag-data/better_money_rag_files/07-privacy-security.md"
touch "backend/docs/rag-data/better_money_rag_files/08-auto.md"
touch "backend/docs/rag-data/better_money_rag_files/09-taxes-income.md"
touch "backend/docs/rag-data/better_money_rag_files/10-college.md"
touch "backend/docs/rag-data/better_money_rag_files/11-life-stages.md"
touch "backend/docs/rag-data/better_money_rag_files/12-url-index.md"
touch "backend/docs/sub_agents.md"
touch "backend/docs/subagent_followups.md"
touch "backend/docs/subagent_rollout.md"
touch "backend/docs/transfer_flow.md"
touch "backend/docs/widget_architecture.md"
touch "backend/docs/widgets.md"
touch "backend/migrations/env.py"
touch "backend/migrations/script.py.mako"
touch "backend/profile/alex_profile.json"
touch "backend/profile/alex_transactions.json"
touch "backend/profile/alex_transactions_by_date.json"
touch "backend/profile/alex_transactions_by_merchant.json"
touch "backend/profile/aria_bank_profile.json"
touch "backend/profile/aria_transactions.json"
touch "backend/profile/aria_transactions_by_date.json"
touch "backend/profile/aria_transactions_by_merchant.json"
touch "backend/profile/chris_profile.json"
touch "backend/profile/chris_transactions.json"
touch "backend/profile/chris_transactions_by_date.json"
touch "backend/profile/chris_transactions_by_merchant.json"
touch "backend/requirements.txt"
touch "backend/run.py"
touch "backend/scripts/bootstrap.py"
touch "backend/scripts/eval_planner_routing.py"
touch "backend/scripts/eval_rows.jsonl"
touch "backend/tests/__init__.py"
touch "backend/tests/test_handoff_and_router.py"
touch "backend/tests/test_presenter_catalog_roundtrip.py"
touch "backend/tests/test_presenter_selector.py"
touch "backend/tests/test_streaming_order.py"
touch "frontend/.env.example"
touch "frontend/.gitignore"
touch "frontend/README.md"
touch "frontend/eslint.config.js"
touch "frontend/index.html"
touch "frontend/package-lock.json"
touch "frontend/package.json"
touch "frontend/playwright.config.js"
touch "frontend/public/favicon.svg"
touch "frontend/public/icons.svg"
touch "frontend/src/App.jsx"
touch "frontend/src/api/client.js"
touch "frontend/src/assets/hero.png"
touch "frontend/src/assets/react.svg"
touch "frontend/src/assets/vite.svg"
touch "frontend/src/components/agents/AgentBuilder.jsx"
touch "frontend/src/components/agents/AgentMenu.jsx"
touch "frontend/src/components/agents/AgentTable.jsx"
touch "frontend/src/components/agents/graph/AddNodeMenu.jsx"
touch "frontend/src/components/agents/graph/AgentCanvas.jsx"
touch "frontend/src/components/agents/graph/NodePropertiesPanel.jsx"
touch "frontend/src/components/agents/graph/nodes/SubAgentNode.jsx"
touch "frontend/src/components/chat/ChatThread.jsx"
touch "frontend/src/components/chat/ConversationList.jsx"
touch "frontend/src/components/layout/AppLayout.jsx"
touch "frontend/src/components/layout/Sidebar.jsx"
touch "frontend/src/components/profiles/ProfileCard.jsx"
touch "frontend/src/components/widgets/AccountSummary.jsx"
touch "frontend/src/components/widgets/ConfirmationRequest.jsx"
touch "frontend/src/components/widgets/GenericComposite.jsx"
touch "frontend/src/components/widgets/ProfileCard.jsx"
touch "frontend/src/components/widgets/RefundForm.jsx"
touch "frontend/src/components/widgets/TextCard.jsx"
touch "frontend/src/components/widgets/TransactionList.jsx"
touch "frontend/src/components/widgets/TransferConfirmation.jsx"
touch "frontend/src/components/widgets/TransferForm.jsx"
touch "frontend/src/components/widgets/WidgetActions.jsx"
touch "frontend/src/components/widgets/WidgetRenderer.jsx"
touch "frontend/src/components/widgets/composites/ProfileWithAccounts.jsx"
touch "frontend/src/index.css"
touch "frontend/src/main.jsx"
touch "frontend/src/pages/AgentBuilderPage.jsx"
touch "frontend/src/pages/AgentsPage.jsx"
touch "frontend/src/pages/ChatPage.jsx"
touch "frontend/src/pages/FilesPage.jsx"
touch "frontend/src/pages/LoginPage.jsx"
touch "frontend/src/pages/ToolsPage.jsx"
touch "frontend/src/pages/WidgetsPage.jsx"
touch "frontend/src/store/agentStore.js"
touch "frontend/src/store/authStore.js"
touch "frontend/src/store/chatStore.js"
touch "frontend/src/store/fileStore.js"
touch "frontend/tests/compound_response.spec.js"
touch "frontend/vite.config.js"
touch "setup.sh"

# Mark the one executable file so scaffolded repo runs right after paste.
chmod +x setup.sh 2>/dev/null || true

echo "Scaffold created at $(pwd)"
echo "Files: 211  directories: 44"
echo ""
echo "Next steps:"
echo "  1. For each file, open the same path on GitHub and paste its contents."
echo "     Browse at https://github.com/emad-noorizadeh/finchat"
echo "  2. Once the files are populated, run ./setup.sh to bootstrap."
