#!/usr/bin/env python3
"""Regenerate ../scaffold.sh from the current `git ls-files` output.

Why this exists:
  Some networks block GitHub. `scaffold.sh` creates the empty folder
  structure + empty files locally so you can then copy each file's
  content from the GitHub web view into the corresponding blank file on
  your machine.

Usage (from the repo root):
  python scripts/gen_scaffold.py > scaffold.sh
  chmod +x scaffold.sh

Run scaffold.sh on your target machine:
  ./scaffold.sh            # creates ./finchat/
  ./scaffold.sh my-dir     # creates ./my-dir/
"""

import subprocess
import sys
from pathlib import Path

HEADER = """#!/usr/bin/env bash
# AUTO-GENERATED by scripts/gen_scaffold.py — do not edit by hand.
# Regenerate with:
#   python scripts/gen_scaffold.py > scaffold.sh && chmod +x scaffold.sh
#
# Purpose:
#   Create the empty folder structure + zero-byte files matching the
#   Erica Agent Platform repo layout. Use when GitHub is blocked on your
#   target network: run this script, then paste each file's content from
#   the GitHub web view into the corresponding blank file.
#
# Usage:
#   ./scaffold.sh                  # creates ./finchat/
#   ./scaffold.sh path/to/dir      # creates ./path/to/dir/
set -eu

TARGET="${1:-finchat}"
if [ -e "$TARGET" ] && [ "$(ls -A "$TARGET" 2>/dev/null)" ]; then
  echo "Refusing to scaffold into non-empty directory: $TARGET" >&2
  echo "Pass a fresh path as the first argument, or delete the existing one." >&2
  exit 1
fi
mkdir -p "$TARGET"
cd "$TARGET"
"""

FOOTER_TPL = """
# Mark the one executable file so scaffolded repo runs right after paste.
chmod +x setup.sh 2>/dev/null || true
chmod +x scripts/gen_scaffold.py 2>/dev/null || true

echo "Scaffold created at $(pwd)"
echo "Files: {n_files}  directories: {n_dirs}"
echo ""
echo "Next steps:"
echo "  1. For each file, open the same path on GitHub and paste its contents."
echo "     Browse at https://github.com/emad-noorizadeh/finchat"
echo "  2. Once the files are populated, run ./setup.sh to bootstrap."
"""


def main() -> int:
    try:
        raw = subprocess.check_output(["git", "ls-files"], text=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("ERROR: must be run inside a git repo with tracked files.", file=sys.stderr)
        return 2

    files = sorted(f for f in raw.splitlines() if f.strip())
    if not files:
        print("ERROR: `git ls-files` returned nothing.", file=sys.stderr)
        return 2

    # Unique parent directories in stable order.
    dirs = sorted({
        str(Path(f).parent)
        for f in files
        if str(Path(f).parent) not in (".", "")
    })

    out = [HEADER]
    out.append("# --- Directories ---")
    for d in dirs:
        out.append(f'mkdir -p "{d}"')
    out.append("")
    out.append("# --- Files (zero-byte) ---")
    for f in files:
        out.append(f'touch "{f}"')
    out.append(FOOTER_TPL.format(n_files=len(files), n_dirs=len(dirs)))

    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
